### ISSUE TITLE
Remove caching from EDBag

### ISSUE THREAD

**Issue by davidwagner** [mikeaboody/phishing-research#108]
Note to self: once the code for updating sender profiles is merged, I should remove all the LRU caches from EDBag.  They probably won't be effective or useful at that point.

**Comment by mikeaboody** [comment]
Without this pull request:

INFO     02/08/2017 17:18:42  Finished training classifier.
INFO     02/08/2017 17:18:42  Starting cross validation.
INFO     02/08/2017 17:18:42  Confusion matrix - True positives: 1217.0, False positives: 16.0, False negatives: 2065.0, True negatives: 3266.0
INFO     02/08/2017 17:18:42  Validation Accuracy: 0.68296770262
INFO     02/08/2017 17:18:42  False positive rate: 0.00487507617307
INFO     02/08/2017 17:18:42  False negative rate: 0.629189518586
INFO     02/08/2017 17:18:42  Starting to test on data.
INFO     02/08/2017 17:18:44  total # of times size of data['message_id'] != sample_size: 0
INFO     02/08/2017 17:18:44  total # of successes: 1243
INFO     02/08/2017 17:18:44  Finished testing on data in 0 minutes, 1 seconds. 2977 directories tested.
INFO     02/08/2017 17:18:44  Memory statistics for 'After generating model':
INFO     02/08/2017 17:18:44  Current total RSS: 189689856
INFO     02/08/2017 17:18:44  Phish Detector took 1 minutes, 43 seconds to run.
INFO     02/08/2017 17:18:44  Summary of multiply-repeated log messages:
INFO     02/08/2017 17:18:44   1479 instances of Creating directory
INFO     02/08/2017 17:18:44  Finished Spear Phishing Detector.

With pull request:
INFO     02/08/2017 17:36:10  Finished training classifier.
INFO     02/08/2017 17:36:10  Starting cross validation.
INFO     02/08/2017 17:36:11  Confusion matrix - True positives: 1248.0, False positives: 16.0, False negatives: 2034.0, True negatives: 3266.0
INFO     02/08/2017 17:36:11  Validation Accuracy: 0.687690432663
INFO     02/08/2017 17:36:11  False positive rate: 0.00487507617307
INFO     02/08/2017 17:36:11  False negative rate: 0.619744058501
INFO     02/08/2017 17:36:11  Starting to test on data.
INFO     02/08/2017 17:36:12  total # of times size of data['message_id'] != sample_size: 0
INFO     02/08/2017 17:36:12  total # of successes: 1243
INFO     02/08/2017 17:36:13  Finished testing on data in 0 minutes, 1 seconds. 2977 directories tested.
INFO     02/08/2017 17:36:13  Memory statistics for 'After generating model':
INFO     02/08/2017 17:36:13  Current total RSS: 186806272
INFO     02/08/2017 17:36:13  Phish Detector took 1 minutes, 46 seconds to run.
INFO     02/08/2017 17:36:13  Summary of multiply-repeated log messages:
INFO     02/08/2017 17:36:13   1479 instances of Creating directory
INFO     02/08/2017 17:36:13  Finished Spear Phishing Detector.

**Comment by mikeaboody** [comment]
Doesn't seem to be too much difference to me, so this can be merged.
