### ISSUE TITLE
Include a ranking of detectors in order of contribution 

### ISSUE THREAD

**Issue by nexusapoorvacus** [mikeaboody/phishing-research#113]
Our results should include a ranking of each detector's contribution in order to make it more clear as to why an email got flagged as phishing. I initially wrote a function (get_top_3_detector_contribution) that would find the top three detectors and save these values in the array returned by "output_phish_probabilities" in classify.py. However, I found an existing method that already finds the detector contributions ("get_detector_contribution" in classify.py). I modified this function so that the mean of each column was subtracted from each data value before the coefficients of linear regression were multiplied. These changes are reflected in bc41782a05636b549a815030a0eeef7a9070380d

I am not sure where the detector contributions should be calculated. For my inbox, the number of emails in the test matrix in output_phish_probabilities has 6 emails, while the test matrix in get_detector_contribution has 140 emails. Why is there this discrepancy?

**Comment by davidwagner** [comment]
Did you figure this out?

**Comment by davidwagner** [comment]
Fixed in PR #125
