### ISSUE TITLE
classify_refactor branch: handle case of email with no FROM header

### ISSUE THREAD

**Issue by davidwagner** [mikeaboody/phishing-research#122]
In the classify_refactor branch, I think ResultRecord might need to handle the case of an email that doesn't have a FROM header.  I got the following traceback when testing the branch:

      File "/home/daw/phishing-research/common/classify.py", line 371, in get_email_records
        records.append(ResultRecord(path, indx[i][0], prob_phish[i][0], test_indx[i][0], test_mess_id[i][0], detector_contribution, header_breakdown))
      File "/home/daw/phishing-research/common/resultRecord.py", line 10, in __init__
        self.email_from = self.all_headers["FROM"]

(Hint for testing: non/ame/noname/legit_emails.log contains some good candidates for emails without a From: header.)

@mikeaboody @nexusapoorvacus

**Comment by nexusapoorvacus** [comment]
Fixed in 4dc741c469a943d5e169f8ff3baa120d25c5fe50 and 01c31ca2bebe3fb4a37ee2d2158f909137ed5d7c
