### ISSUE TITLE
classify_refactor branch: mbox stuff might need to uppercase all header names

### ISSUE THREAD

**Issue by davidwagner** [mikeaboody/phishing-research#123]
Does the mbox parsing code path need to uppercase header names?

Right now, when using a mbox, I see some emails where the 'From:' header is not uppercased (it is listed as 'from' instead of 'FROM' in legit_emails.log).  Also it looks like get_email_records() and to_dictionary() in classify.py don't uppercase header names.

As a result, I expect some things may go wrong: From/Subject headers might be missed.

Check my reasoning here.

@mikeaboody @nexusapoorvacus

**Comment by nexusapoorvacus** [comment]
Yes, mboxToFile.py in broScripts was not writing the header names in upper case which caused errors when trying to access from and subject headers. This was fixed in c86657755a276fa6f1b704d3bdd708c9fc7b1b39
