### ISSUE TITLE
Inbox should preserve order

### ISSUE THREAD

**Issue by davidwagner** [mikeaboody/phishing-research#14]
Inbox should preserve the order of the headers correctly, even when some headers are repeated: e.g., Received, Message-ID, Received.

**Comment by davidwagner** [comment]
Oops, I meant Email, not Inbox.

**Comment by mikeaboody** [comment]
Potentially fixed in ac0bbabd8be21332bd83236c7bc0864fd2694bbb

**Comment by davidwagner** [comment]
Doesn't look fixed to me.  Consider:

```
Received: x
X-Foo: y
Received: z
```

After parsing this, it looks like it's going to be treated as if it were

```
Received: x
Received: z
X-Foo: y
```

which is not the same.  This might mess up Jenna's detector or make it perform worse.

Possible implementation strategy: keep the list of (header name, header value) pairs (i.e., `headers_arg`).  Then, maintain a dict that given a header name finds the index of all its  occurrences in that list.

**Comment by mikeaboody** [comment]
Is this not the intended behavior? Which part of the code is treating it that way?
<img width="499" alt="screen shot 2016-05-09 at 2 00 12 pm" src="https://cloud.githubusercontent.com/assets/5702907/15128060/8632c324-15ee-11e6-8a03-19f46cc5a378.png">

**Comment by davidwagner** [comment]
I can't see any way to iterate through (k,v) pairs in the correct order: that information is discarded.

Ahh, I see.  None of our detectors currently needs that information, so even though Email doesn't fully preserve ordering information, we can get away with it for what we're doing right now.  OK, never mind.
