### ISSUE TITLE
Inbox getitem() should return only one value

### ISSUE THREAD

**Issue by davidwagner** [mikeaboody/phishing-research#15]
Inbox's **getitem**() should return only the first header value, if there are multiple (e.g., if a header name is duplicated).

**Comment by davidwagner** [comment]
Oops, I meant Email's `__getitem__()`, not Inbox.

**Comment by mikeaboody** [comment]
Potentially fixed in ac0bbabd8be21332bd83236c7bc0864fd2694bbb

**Comment by davidwagner** [comment]
LGTM
