### ISSUE TITLE
Generate log of scores for all emails

### ISSUE THREAD

**Issue by davidwagner** [mikeaboody/phishing-research#17]
./runall should generate a text file that has the score for every email: e.g., one line per email, containing the message ID and the score from the classifier (tab-separated or comma-separated).

**Comment by nexusapoorvacus** [comment]
The branch emailScoresFile has code that generates a text file (email_probabilities.txt) in common/output folder when `python spear_phishing_detector.py --all` is run. There is one line per email with the email's message_ID and probability it is a phish. These values are comma separated. The file gets overwritten every time spear_phishing_detector.py is run and the file is created if it doesn't exist initially. Here is the commit: 330af84e5cc8bd907b2561cf79391e348d973368.

**Comment by davidwagner** [comment]
Cool.  Apoorva, can you create a pull request, get a review from Matt or Michael, and merge?  Thanks!

**Comment by nexusapoorvacus** [comment]
Sure! Its at PR #46

**Comment by nexusapoorvacus** [comment]
Merged! 5fe89e92e6a5a01bb77928463a1a64a5bda58929
