### ISSUE TITLE
Deal with / in email addresses

### ISSUE THREAD

**Issue by davidwagner** [mikeaboody/phishing-research#19]
I bet if the sender email address contains a slash (`/`), the code is going to break when trying to store this on the filesystem, because `/` cannot appear in filenames (it is the directory separator).

It's probably sufficient to just omit all slashes from the filename you use.

Possible fix: write a single function `emailaddr_to_filename()` that is responsible for doing all of the work to convert an email address to something that can be used in a filename; this might strip all `/`'s and truncate to 100 characters.

**Comment by nexusapoorvacus** [comment]
I stripped the `/`'s on the folder names we create. The folder names are based on the sender's name and the sender's email. The file names are created by us (legit_emails.log and phish_emails.log) so there won't be any `/`'s in them.
Commit: 1bac9bc29b0702ae0b78249cdd2add746e11441b

**Comment by davidwagner** [comment]
Cool!

Don't you need to do the same thing for lines 165,166,170,171 of parse_pcap.py (the part of generating phish emails)?

**Comment by nexusapoorvacus** [comment]
Yes, you are right. I just fixed it: 973008eacbd1fd19a215c231031fdd04489604a4
