### ISSUE TITLE
Email.get_all() throws if there is no such header

### ISSUE THREAD

**Issue by davidwagner** [mikeaboody/phishing-research#20]
In the `Email` class, `__getitem__(h)` returns `None` if there is no header with the name `h`.  However, `get_all(h)` throws `KeyError` if there is no header with name `h` (due to evaluating `self.header_dict[key.upper()]` without first testing for the possibility `key.upper() not in self.header_dict`).

Is this the correct behavior?  It seems inconsistent with `__getitem__()`, and it pushes the responsibility onto all callers of `get_all()` to catch this error.  I think it would be better to return an empty list if there is no header with this name.

**Comment by mikeaboody** [comment]
This is definitely incorrect behavior (and probably the cause of our most recent error). You are right, get_all should return an empty list. This will resolve the issue of having no Received headers in an email as a call to get_all will return an empty list, which the algorithm can handle.

**Comment by mikeaboody** [comment]
Potentially fixed in ac0bbabd8be21332bd83236c7bc0864fd2694bbb

**Comment by davidwagner** [comment]
LGTM
