### ISSUE TITLE
Email.values() and .items() look like they do something bogus for repeated headers

### ISSUE THREAD

**Issue by davidwagner** [mikeaboody/phishing-research#21]
In the `Email` class, `items()` and `values()` look like they do strange things for headers that are repeated.

Instead of the current behavior, if a header is repeated, I think it would be better for `items()` to return multiple items, one per line.  For instance, if we have

```
Received: x
Message-ID: y
Received: z
```

I think it would be better for `items()` to return the list

```
[('Received', 'x'), ('Message-ID', 'y'), ('Received', 'z')]
```

Right now it returns

```
[('Received', ['x', 'z']), ('Message-ID', 'y')]
```

which is a bit weird and sounds like a recipe for bugs in our detectors.

Similarly for `values()`, though I'm not sure `values()` is useful -- does anyone use `values()`?  Perhaps it would be better to have `values()` throw NotImplemented, to document that people should avoid using `values()` (given that it is probably not useful, and its semantics when header names are repeated are odd).

**Comment by mikeaboody** [comment]
I don't believe either is used (by a simple call to grep), so I threw NotImplemented for both in ac0bbabd8be21332bd83236c7bc0864fd2694bbb

**Comment by davidwagner** [comment]
Sounds like a good fix.
