### ISSUE TITLE
Inbox.sort_emails() probably breaks if the Date header is missing

### ISSUE THREAD

**Issue by davidwagner** [mikeaboody/phishing-research#22]
In the `Inbox` class, `compare_emails()` assumes both emails have a `Date` header.  If either email has no `Date` header, it will throw a KeyError, which will make `sort_emails()` fail and throw.  That's bad, as I wouldn't be shocked if we encounter some emails that don't have any `Date` header.

I think this should be written to handle gracefully the case of emails with no `Date` header, perhaps treating them as occurring at some default date (Jan 1, 1970?) for sorting purposes.

**Comment by mikeaboody** [comment]
I believe this was handled correctly (I tested a while back for this and I believe we talked about it in one of our meetings). Even if Email.**getitem** returns None for the Date header, I still have None checks for  the date:

```
if date_header1 == date_header2: #if both are None, then they're equal
    return 0
if not date_header1 or not email.utils.parsedate(date_header1): #elif date_header1 is None, date_header1 < date_header2
    return 1
if not date_header2 or not email.utils.parsedate(date_header2): #elif date_header2 is None, date_header1 > date_header2
    return -1
```

**Comment by davidwagner** [comment]
Oops, my mistake.  Sorry about that.
