### ISSUE TITLE
Email __getitem__() should return only one header

### ISSUE THREAD

**Issue by davidwagner** [mikeaboody/phishing-research#24]
In the class `Email`, if there are multiple headers with the same name (key), then it seems like `__getitem__()` should probably return the value of only a single one of them (say, the first, or an arbitrary one).  It current returns a list of all values, if there are duplicates.  This is ugly:
- It appears to differ from semantics of Python's mailbox (?)
- It means that each caller has to explicitly check for the rare case where it returns a list of values instead of a value.  I bet a lot of callers won't remember to check for this (leading to potential hard-to-diagnose rare bug); and if they do check, their code gets uglier and unwieldy.

Would it be cleaner to return only a single value, e.g., just the first?

**Comment by mikeaboody** [comment]
Forgot to comment on this one too. Potentially fixed a few days ago in ac0bbabd8be21332bd83236c7bc0864fd2694bbb

**Comment by davidwagner** [comment]
Looks good to me
