### ISSUE TITLE
mbox_to_file_directory getHeadersTupleList() doesn't preserve order of headers

### ISSUE THREAD

**Issue by davidwagner** [mikeaboody/phishing-research#26]
getHeadersTupleList() re-orders the headers: when some header name appears more than once, its order is not preserved.  e.g., consider

```
Received: x
X-Whatever: y
Received: z
```

It looks like getHeadersTupleList() will re-order this to

```
Received: x
Received: z
X-Whatever: y
```

which is wrong.  This might throw off Jenna's detector based on the order of the headers.  Our code should preserve the order of headers.

**Comment by mikeaboody** [comment]
I fixed this a few days ago. Forgot to push it. My bad!

**Comment by mikeaboody** [comment]
Actually, I had pushed this in ae3b49ed0ef95a11d3d4ad4fe4345e002201410a a few days ago. Did this not solve the problem? I tested this a few days ago to make sure the order was right and it was exactly what it should have been.

**Comment by davidwagner** [comment]
LGTM
