### ISSUE TITLE
Descriptive error messages for pcap parser

### ISSUE THREAD

**Issue by davidwagner** [mikeaboody/phishing-research#34]
I think our last run found that a bunch of emails were getting ignored because of parse errors encountered by the pcap parser.

Let's add some sanity-checking and diagnosis code when parsing a pcap, so that when we encounter a parse error, we output an error message that is descriptive enough that it gives us some idea what the problem in our code is, yet is safe for Vern to copy-paste (doesn't include any confidential/sensitive information from header values).  If we can identify a few categories of types of parse errors, it'd also be good to report aggregate statistics: the number of parse errors of each type.

This will facilitate the 'outsourced execution' model.

**Comment by nexusapoorvacus** [comment]
New parse error detection and logging to stdout is added in PR #38. The error statements that are printed to stdout are not safe for Vern to copy-paste to us. But when logging is integrated, the confidential/sensitive information will be logged to a different file that Vern can keep and unsensitive information will be logged in a separate file that he can send to us.
