### ISSUE TITLE
Produce memory usage statistics

### ISSUE THREAD

**Issue by davidwagner** [mikeaboody/phishing-research#35]
The code should periodically output some memory usage statistics, both total memory usage, as well as a breakdown by key data structures. 

See email thread.  e.g., in Classify.test_and_report() profile and output a summary once every 100,000 iterations of the loop and report total memory usage +  amount of memory used by `results`; in PhishDetector.generate_features(), profile once every 100,00 senders and report total memory usage.

Michael, I suggest you work out a reasonable plan for some useful aggregate values you can report in the periodic memory-usage report, and implement.  Goal is for us to be able to identify which data structures account for the bulk of memory usage, and to be able to use a run on ICSI data to extrapolate to predicted memory usage needed for a run on the full data set from our enterprise partner.

**Comment by mikeaboody** [comment]
https://github.com/mikeaboody/phishing-research/pull/36 might do the trick based on our previous meeting where we decided to go with profiling every X amount of time instead of every X amount of iterations.
