### ISSUE TITLE
Cut down on log spam

### ISSUE THREAD

**Issue by davidwagner** [mikeaboody/phishing-research#47]
Right now we get massive log spam, one line per directory, e.g.,

```
Creating Directory #1
Creating Directory #2
...
```

and

```
Data and features generated for directory #1
Data and features generated for directory #2
...
```

As we scale up, the number of senders (directories) is going to be immense -- millions -- which will cause log spam.  Probably we should change the code to only output this log line once every minute, or something like that.

**Comment by MatthewChow** [comment]
Should be fixed by https://github.com/mikeaboody/phishing-research/pull/48. We'll output the first set of logs once every 60 seconds, and eliminate the second set of logging completely (there's already logging during that portion of the pipeline that should be sufficient).
