### ISSUE TITLE
Minor: XMailerDetector possible performance improvement

### ISSUE THREAD

**Issue by davidwagner** [mikeaboody/phishing-research#60]
The algorithm used by XMailerDetector is O(n^2) where n = number of different xmailer values (after removing version numbers etc.) for a particular sender.  Hopefully the number of xmailer values will be small for most senders and so this probably won't matter much in practice, I'm guessing... but:

This algorithm could be sped up.  One could build a set or dict of the xmailer.lower() values seen (and None, if seen), then look up in the set.

Hopefully won't matter in practice, unless we see particularly perverse X-Mailer header values.

**Comment by mikeaboody** [comment]
I don't know how likely this is to help performance, but perhaps it's possible if an attacker tries to give itself a lot of different x-mailers. Let me try it out.
