### ISSUE TITLE
message_ID_domain.py orgGroups() logic errors and code review

### ISSUE THREAD

**Issue by davidwagner** [mikeaboody/phishing-research#72]
orgGroups() in message_ID_domain.py seems to have some logic errors.

- It invokes getBinaryRep() but getBinaryRep() is never defined or imported,
  so any attempt to call it is just going to trigger an exception and cause
  execution of the exception handler -- probably not what was desired.

- try: .. except: .. is considered bad practice because it catches all
  exceptions.  try: .. except Exception: .. is a bit better if you have
  to catch all exceptions, but it's better to catch specific exception
  types.

- I suspect the following lines

    ip1 = Lookup.seen_domain_ip[newmID]
    res11 = getBinaryRep(ip1, Lookup.getCIDR(ip1))

  should have been

    ip1 = Lookup.seen_domain_ip[newmID]
    res11 = Lookup.getCIDR(ip1)

  Also I suspect this should check for membership before looking up
  in Lookup.seen_domain_ip, to avoid throwing an exception.

- Minor: the memoization seems like it's making the code more
  complex.  It might not be necessary to do all this memoization,
  as the unmemoized computation is fairly simple and basically just
  a few lookups.

- The following code is probably going to do the wrong thing if
  sender doesn't contain an '@':

    afterAT = mID
    afterAT = sender[sender.index("@")+1:]

  In particular, it'll add a strange entry to self.domain2domainPairing.
  Maybe better to check for this case explicitly and do something
  reasonable in that case?

**Comment by nexusapoorvacus** [comment]
The logic errors in orgGroups should be addressed in the following commit 90fd36e2ae2fe5ca1c9835b50a804d7363789996
