### ISSUE TITLE
ReceivedHeadersDetector doesn't use receiver

### ISSUE THREAD

**Issue by davidwagner** [mikeaboody/phishing-research#86]
ReceivedHeadersDetector looks designed to have one profile per sender/receiver pair.  However, as actually implemented, it always sets receiver="", so it effectively has one profile per sender.  Which is the right thing to do?

I expect that in principle the mail path (sequence of received headers) could depend on both the sender and the receiver.  However, in the context where we're seeing emails, it probably won't depend on the receiver (or not much), as we see the email as it flows into the organization, and the receiver is always within the organization, so the path the email flows before it enters the organization is the same for all recipients within that organization.  If that's right, then that seems to suggest that the current implementation (ignore the receiver; one profile per sender) seems reasonable, and there's no need to have a profile per (sender,receiver) pair.  What do you think?

Cc: @mikeaboody , @nexusapoorvacus

**Comment by nexusapoorvacus** [comment]
We decided to ignore the receiver and just have a profile for every sender. I don't remember why exactly we designed it this way, but your reasoning for why this implementation should work, makes sense.
