### ISSUE TITLE
Need to chronologically sort .pcap's

### ISSUE THREAD

**Issue by davidwagner** [mikeaboody/phishing-research#92]
If there are multiple pcaps, right now we just do a file glob and read them in whatever order the glob returns.  We should instead be sorting them in chronological order and reading them in that order, so that we read emails in the order of the time they were sent/received.

Not critical yet because right now we've been testing with only a single .pcap, but we'll need to fix this in the future.

**Comment by MatthewChow** [comment]
Do you think it makes sense to enforce that the network administrator (or whoever is running our software) must follow some naming convention such that it's easy for our script to determine time orderings? (i.e. `data0.pcap`, `data1.pcap`, etc.) Or do you think it makes more sense for our script to detect the chronological ordering? (potentially by doing something like `stat [FILENAME]` and ordering based off of when the file was modified or created).

**Comment by davidwagner** [comment]
It seems reasonable to me to adopt a naming convention for .pcap's.

I don't think we can count on `stat filename` to give us a correct chronological ordering, as if the .pcap's have been copied from somewhere else the file creation time might not match the original time when the packets were captured from the network.

**Comment by davidwagner** [comment]
I added code to sort the .pcap files by whatever Python's sort order is.  We'll need to remember Vern to pick a naming convention for .pcap's that makes sure this gives them the right order.
