### ISSUE TITLE
--mbox isn't working right

### ISSUE THREAD

**Issue by davidwagner** [mikeaboody/phishing-research#93]
With --mbox, we get cross-validation accuracy = 0.50.  With using mbox_to_file_directory.py, we get much better cross-validation accuracy (say, 0.87).  So there is some discrepancy between those two.  This suggests that --mbox is doing something wrong; it's not creating the directory structure or training matrix correctly somehow.

@mikeaboody , @nexusapoorvacus

**Comment by davidwagner** [comment]
Ahh.  I bet this is caused by bug #95.

**Comment by MatthewChow** [comment]
@mikeaboody I fixed https://github.com/mikeaboody/phishing-research/issues/95; can you pull from master again and re-run both approaches to verify that the cross-validation accuracy is consistent across both methods? Thanks!

**Comment by nexusapoorvacus** [comment]
I just pulled from master and ran the detector with the --mbox flag. For this approach, I get a Validation Accuracy of 91.3%, False positive rate: 3.43%, and a False negative rate of 14%. I also ran the detector with the mbox_to_file_directory.py script and I get the following results: Validation Accuracy: 92.6%, False positive rate: 3.37%, False negative rate: 11.4%. I think the cross-validation accuracy with --mbox seems to be consistently around 1% less than the mbox_to_file_directory.py method, but this is probably not a significant difference.

**Comment by mikeaboody** [comment]
Running and validation is 87% with yours and 86% with mine, so it seems like it's working.
