### ISSUE TITLE
Senders might not be shuffled -- shuf doesn't do what you'd think it does

### ISSUE THREAD

**Issue by davidwagner** [mikeaboody/phishing-research#95]
We call

        os.system('shuf {} > /dev/null'.format(SENDERS_FILE))

The problem is that the `shuf` program reads from the specified file and then writes a shuffled version to stdout.  It doesn't update the file specified on the command line.  Since we're redirecting stdout to /dev/null, we're throwing away the shuffled output and leaving senders.log unchanged (unshuffled).  Consequently, the phish_emails.log file that is generated ends up being exactly identical to legit_emails.log; the From: line hasn't been randomized, but is left 100% unchanged.

This would explain why we're getting different results from --mbox vs mbox_to_file_directory.py, as --mbox uses the command-line `shuf` utility while mbox_to_file_directory.py uses Python's `random.shuffle()` function.

This would explain why we're getting cross-validation accuracy of 50% with --mbox, as the "simulated phishing" emails we're generating are inadvertently exactly equal to the legitimate original emails.

The solution is to write the output from `shuf` to another file (`senders_shuffled.log` ?) and then read from that when generating phish_emails.log.

@nexusapoorvacus , @mikeaboody , @MatthewChow

**Comment by MatthewChow** [comment]
https://github.com/mikeaboody/phishing-research/pull/97 should do the trick. I described how I tested it in the PR linked.
