### ISSUE TITLE
Cross-validation accuracy seems surprisingly low; need to investigate

### ISSUE THREAD

**Issue by davidwagner** [mikeaboody/phishing-research#96]
Michael saw cross-validation accuracy of 87% when using mbox_to_file_directory.py on his personal inbox.  This seems surprisingly low, compared to the accuracy we were getting before.  We were previously getting a false positive rate of 1 in 10,000 or so (though the false negative rate was significant).

Is this as bad as it seems?  Let's break down the 87% accuracy more granularly -- what is the false negative rate and false positive rate?  (A false negative rate of 26% and false positive rate of 1 in 10,000 would be fine.  But a false negative rate of 13% and false positive rate of 13% would be terrible.)

Let's investigate and see if we can figure out what's going on here.

It's also possible this might be related to the class weights.  If we increase the class weight on negatives, does that reduce the false positive rate?  See also bug #85.

**Comment by mikeaboody** [comment]
Let me record some statistics now that I found that we fixed the shuffle bug.

**Comment by mikeaboody** [comment]
**Weights: 0.5 to 1.0**
INFO     12/07/2016 12:00:30  Confusion matrix - True positives: 2520.0, False positives: 103.0, False negatives: 772.0, True negatives: 3189.0
INFO     12/07/2016 12:00:30  Validation Accuracy: 0.867102065614
INFO     12/07/2016 12:00:30  False positive rate: 0.0312879708384
INFO     12/07/2016 12:00:30  False negative rate: 0.234507897934

**Weights: 0.1 to 1.0**
INFO     12/07/2016 12:02:49  Confusion matrix - True positives: 2331.0, False positives: 41.0, False negatives: 961.0, True negatives: 3251.0
INFO     12/07/2016 12:02:49  Validation Accuracy: 0.847812879708
INFO     12/07/2016 12:02:49  False positive rate: 0.0124544349939
INFO     12/07/2016 12:02:49  False negative rate: 0.29191980558

**Weights: 0.01 to 1.0**
INFO     12/07/2016 12:05:25  Confusion matrix - True positives: 1192.0, False positives: 5.0, False negatives: 2100.0, True negatives: 3287.0
INFO     12/07/2016 12:05:25  Validation Accuracy: 0.680285540705
INFO     12/07/2016 12:05:25  False positive rate: 0.00151883353584
INFO     12/07/2016 12:05:25  False negative rate: 0.637910085055

**Weights: 0.001 to 1.0**
INFO     12/07/2016 12:07:23  Confusion matrix - True positives: 547.0, False positives: 0.0, False negatives: 2745.0, True negatives: 3292.0
INFO     12/07/2016 12:07:23  Validation Accuracy: 0.583080194411
INFO     12/07/2016 12:07:23  False positive rate: 0.0
INFO     12/07/2016 12:07:23  False negative rate: 0.833839611179

**Comment by mikeaboody** [comment]
I feel like this is consistent with the original results that we had. Remember that we decided to prioritize a low false alarm rate for a mediocre detection rate, and it seems like these are the weights in which that was produced. 

Can we truly base our results off of solely the validation accuracy?

**Comment by davidwagner** [comment]
Thanks for testing this!

I agree, the false positive rate & false negative rates are more important than overall validation accuracy.

It's a little concerning that our false negative rates are so high.

I can't seem to find my records of the false alarm rate and detection rate (false negative rate) we had before.  The false positive rates sound consistent with what I remember us seeing before.  The false negative rates sound worse.  I think I have a vague recollection that at a weight of 0.001 to 1 (1 to 1000), we previously had seen a false positive rate of 10^-5 and detection rate mediocre (maybe 50-70% ish?).  At a weight of 0.001, it looks like we're currently getting a false positive rate that might be consistent with that but a detection rate that's much worse: only 17% detection rate (83% false negative means we're detecting only 17% of attacks, i.e., detection rate of only 17%).

I wonder if detection rate has gotten worse somehow?

**Comment by mikeaboody** [comment]
It's possible. I don't remember fully. Do you remember @MatthewChow?
